FROM node:latest

WORKDIR /usr/src/app
COPY typescript/package*.json ./
COPY typescript/tsconfig.json ./
RUN npm install
RUN npm install -g nodemon
# RUN npx tsc --init
EXPOSE 3000
ENTRYPOINT /bin/bash